Fixing race condition caused by missing wait on bash subcommand

diff --git a/snapdir b/snapdir
--- a/snapdir
+++ b/snapdir
@@ -242,7 +242,8 @@ snapdir_push() {
 			if [[ $verbose == "true" ]]; then
 				verbose_flag="set -x;"
 			fi
-			bash -c "set -eEuo pipefail;${verbose_flag}${push_command}" | _snapdir_log
+			bash -c "set -eEuo pipefail;${verbose_flag}${push_command}
+			wait" | _snapdir_log
 		fi
 	else
 		_snapdir_log "Nothing to push to '${store}'."
@@ -317,7 +318,9 @@ snapdir_fetch() {
 		if [[ ${dryrun} == "true" ]]; then
 			_snapdir_dryrun_log "${fetch_files_commands}"
 		else
-			bash -c "set -eEuo pipefail;${fetch_files_commands}" >"$_output_dest" || {
+			bash -c "set -eEuo pipefail;
+			${fetch_files_commands}
+			wait" >"$_output_dest" || {
 				rm -rf "${manifest_cache_path}.${tmp_id}"
 				echo "error: Failed to fetch files for snapshot '${snapdir_id}' from store '${store}' when calling '${fetch_files_commands}'." >&2
 				return 1
@@ -610,7 +613,7 @@ snapdir_verify() {
 		failed_objects="$(echo "$result" | grep -E ': FAILED' | cut -d ':' -f1 | tr '\n' ' ')"
 		echo "$result"
 		if [[ ${failed_objects:-""} != "" ]]; then
-			echo "$failed_objects" | xargs rm
+			echo "$failed_objects" | xargs rm -f
 			return 1
 		fi
 	else
