Adding s3 integration test

diff --git a/snapdir b/snapdir
--- a/snapdir
+++ b/snapdir
@@ -449,8 +449,9 @@ snapdir_checkout() {
 	done <"${manifest_cache_path}"
 
 	if [[ ${dryrun} == "true" ]]; then
-		for directory in "${directories[@]}"; do
-			_snapdir_dryrun_log "mkdir -p \"$directory\""
+		# using safe idiom to iterate over arrays on bash >= 4.0
+		for ((i = 0; i < ${#directories[@]}; i++)); do
+			_snapdir_dryrun_log "mkdir -p \"${directories[$i]}\""
 		done
 
 		if [[ ${_SNAPDIR_LINKED:-false} == true ]]; then
@@ -466,8 +467,9 @@ snapdir_checkout() {
 			done
 		fi
 	else
-		for directory in "${directories[@]}"; do
-			mkdir -p "$directory"
+		# using safe idiom to iterate over arrays on bash >= 4.0
+		for ((i = 0; i < ${#directories[@]}; i++)); do
+			mkdir -p "${directories[$i]}"
 		done
 
 		if [[ ${_SNAPDIR_LINKED:-false} == true ]]; then
@@ -486,8 +488,9 @@ snapdir_checkout() {
 
 	if [[ ${_SNAPDIR_VERBOSE:-""} == "true" ]]; then
 		# print success messages
-		for message in "${success_messages[@]}"; do
-			_snapdir_log "$message"
+		# using safe idiom to iterate over arrays on bash >= 4.0
+		for ((i = 0; i < ${#success_messages[@]}; i++)); do
+			_snapdir_log "${success_messages[$i]}"
 		done
 	fi
 }
@@ -721,17 +724,17 @@ _snapdir_get_store_bin_path() {
 		echo "${!explicit_bin_path}"
 		return 0
 	fi
-	store_bin_path=$(which "snapdir-${store_protocol}-store" || echo "" 2>/dev/null)
+	if test -f "${_SNAPDIR_BIN_DIR}/snapdir-${store_protocol}-store"; then
+		echo "${_SNAPDIR_BIN_DIR}/snapdir-${store_protocol}-store"
+		return 0
+	fi
+	store_bin_path=$("snapdir-${store_protocol}-store" -v || echo "" 2>/dev/null)
 	if [[ ${store_bin_path} == "" ]]; then
-		if test -f "${_SNAPDIR_BIN_DIR}/snapdir-${store_protocol}-store"; then
-			echo "${_SNAPDIR_BIN_DIR}/snapdir-${store_protocol}-store"
-			return 0
-		fi
 		echo "Unsupported store protocol: ${store_protocol}" >&2
 		echo "No 'snapdir-${store_protocol}-store' could be found on your PATH" >&2
 		return 1
 	fi
-	echo "$store_bin_path"
+	echo "${store_bin_path}"
 }
 
 _snapdir_get_push_command() {
@@ -860,7 +863,6 @@ _snapdir_export_env_defaults() {
 	_SNAPDIR_FORCE=${_SNAPDIR_FORCE:-"false"}
 	_SNAPDIR_CWD="${_SNAPDIR_CWD:-$(pwd)}"
 	_SNAPDIR_BIN_DIR="$(dirname "${_SNAPDIR_BIN_PATH}")"
-
 	_snapdir_set_manifest_from_stdin_or_id
 	_snapdir_export_store_vars
 
@@ -1302,17 +1304,18 @@ _snapdir_absolute_path() {
 	realpath -m "$1"
 }
 
+if [[ ${BASH_VERSION:0:1} -lt "4" ]]; then
+	echo "Bash version 4.0 or higher is required. You have: ${BASH_VERSION}" >&2
+	exit 1
+fi
+
 if [[ "$(uname -s)" == "Darwin" ]]; then
 	# ensure at least bash 5.0 is available
-	if [[ ${BASH_VERSION:0:1} -lt "5" ]]; then
-		echo "Bash version 5.0 or higher is required. You have: ${BASH_VERSION}" >&2
-		exit 1
-	fi
 	_snapdir_readlink() {
 		echo "$(cd "$(dirname "$1")" || echo "" && pwd)/$(basename "$1")"
 	}
 else
-	shopt -s inherit_errexit
+
 	_snapdir_is_bussybox="$(test -h /bin/ls && echo true || echo false)"
 	_snapdir_readlink() {
 		readlink -f "$1"
diff --git a/snapdir-b2-store b/snapdir-b2-store
--- a/snapdir-b2-store
+++ b/snapdir-b2-store
@@ -367,9 +367,6 @@ _snapdir_get_transfer_objects_command() {
 
 	if [[ $total_files -eq 0 ]]; then
 		echo 'echo "No new objects to fetch.";'
-	else
-		# wait for individual commands to finish
-		echo "wait -n;"
 	fi
 }
 
@@ -485,13 +482,13 @@ snapdir_b2_store_test() (
 
 		export PATH="$HOME/.cache/snapdir/bin:$PATH"
 		{
-			which b2 >/dev/null || {
+			b2 version >/dev/null || {
 				mkdir -p "$HOME/.cache/snapdir/bin"
 				local bin_path="b2-linux"
 				if [[ "$(uname -s)" == "Darwin" ]]; then
 					bin_path="b2-darwin"
 				fi
-				https://github.com/Backblaze/B2_Command_Line_Tool/releases/download/v3.4.0/b2-linux
+
 				wget -q "https://github.com/Backblaze/B2_Command_Line_Tool/releases/download/v3.4.0/${bin_path}" -O "$HOME/.cache/snapdir/bin/b2" || {
 					echo "ERROR: Failed to download b2 binary" >&2
 					rm -rf "$HOME/.cache/snapdir/bin/b2"
@@ -503,6 +500,7 @@ snapdir_b2_store_test() (
 					exit 1
 				}
 			}
+			b2 version
 			echo "authorizing b2 account"
 			echo "this integration test requires network connectivity and valid b2 credentials"
 			b2 authorize-account "${SNAPDIR_B2_STORE_APPLICATION_KEY_ID}" "${SNAPDIR_B2_STORE_APPLICATION_KEY}"
@@ -729,8 +727,15 @@ if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
 	export _SNAPDIR_B2_STORE_BIN_PATH="${_SNAPDIR_B2_STORE_BIN_PATH:-$(_snapdir_b2_store_readlink "${BASH_SOURCE[0]}")}"
 	# import snapdir functions and environment variables,
 	# we'll need them to resolve directories, logging and testing.
-	_SNAPDIR_BIN_PATH="$(which snapdir || echo "$(dirname "${_SNAPDIR_B2_STORE_BIN_PATH}")/snapdir")"
-	export _SNAPDIR_BIN_PATH
+	_SNAPDIR_BIN_PATH="$(dirname "${_SNAPDIR_B2_STORE_BIN_PATH}")/snapdir"
+	if ! test -f "$_SNAPDIR_BIN_PATH"; then
+		if snapdir -v 2>/dev/null >/dev/null; then
+			_SNAPDIR_BIN_PATH="snapdir"
+		else
+			echo "error: Could not find snapdir binary"
+			exit 1
+		fi
+	fi
 	# shellcheck disable=SC1090
 	. "$_SNAPDIR_BIN_PATH"
 	snapdir_b2_store_run "${@:1}"
diff --git a/snapdir-file-store b/snapdir-file-store
--- a/snapdir-file-store
+++ b/snapdir-file-store
@@ -306,9 +306,6 @@ _snapdir_get_transfer_objects_command() {
 
 	if [[ $total_files -eq 0 ]]; then
 		echo "echo \"No new objects to ${operation_type}.\";"
-	else
-		# wait for individual object commands to finish
-		echo "wait -n;"
 	fi
 }
 
@@ -671,7 +668,7 @@ if [[ "$(uname -s)" == "Darwin" ]]; then
 		echo "$(cd "$(dirname "$1")" || echo "" && pwd)/$(basename "$1")"
 	}
 else
-	shopt -s inherit_errexit
+
 	_snapdir_file_store_readlink() {
 		readlink -f "$1"
 	}
@@ -691,8 +688,15 @@ if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
 	export _SNAPDIR_FILE_STORE_BIN_PATH="${_SNAPDIR_FILE_STORE_BIN_PATH:-$(_snapdir_file_store_readlink "${BASH_SOURCE[0]}")}"
 	# import snapdir functions and environment variables,
 	# we'll need them to resolve directories, logging and testing.
-	_SNAPDIR_BIN_PATH="$(which snapdir || echo "$(dirname "${_SNAPDIR_FILE_STORE_BIN_PATH}")/snapdir")"
-	export _SNAPDIR_BIN_PATH
+	_SNAPDIR_BIN_PATH="$(dirname "${_SNAPDIR_FILE_STORE_BIN_PATH}")/snapdir"
+	if ! test -f "$_SNAPDIR_BIN_PATH"; then
+		if snapdir -v 2>/dev/null >/dev/null; then
+			_SNAPDIR_BIN_PATH="snapdir"
+		else
+			echo "error: Could not find snapdir binary"
+			exit 1
+		fi
+	fi
 	# shellcheck disable=SC1090
 	. "$_SNAPDIR_BIN_PATH"
 	snapdir_file_store_run "${@:1}"
diff --git a/snapdir-s3-store b/snapdir-s3-store
--- a/snapdir-s3-store
+++ b/snapdir-s3-store
@@ -152,7 +152,7 @@ snapdir_s3_store_get_fetch_files_command() {
 		fi
 	} | _snapdir_get_transfer_objects_command "${source_dir}" "${target_dir}" "fetch" "${log_file}"
 
-	echo "${_SNAPDIR_S3_STORE_BIN_PATH} ensure-no-errors --checksum \"${id}\" --log-file \"$log_file\";"
+	echo "${_SNAPDIR_S3_STORE_BIN_PATH} ensure-no-errors --store \"$store\" --checksum \"${id}\" --log-file \"$log_file\";"
 }
 
 ######  #     # ######  #       ###  #####     ####### #     #  #####
@@ -186,8 +186,8 @@ snapdir_s3_store_get_manifest() {
 	# creates a temporary file to log the output of the transaction
 	tmp_manifest_path="$(mktemp -t "snapdir-manifest-${id}".XXXXXXXXXX)"
 
-	${_SNAPDIR_S3_STORE_BIN_PATH} fetch --checksum "${id}" --source-path "${manifest_rel_path}" --target-path "${tmp_manifest_path}" --log-file "$log_file" --store "${store}" --retries "${retries}" >/dev/null
-	${_SNAPDIR_S3_STORE_BIN_PATH} ensure-no-errors --checksum "${id}" --log-file "$log_file" || {
+	${_SNAPDIR_S3_STORE_BIN_PATH} fetch --store "${store}" --checksum "${id}" --source-path "${manifest_rel_path}" --target-path "${tmp_manifest_path}" --log-file "$log_file" --store "${store}" --retries "${retries}" >/dev/null
+	${_SNAPDIR_S3_STORE_BIN_PATH} ensure-no-errors --store "${store}" --checksum "${id}" --log-file "$log_file" || {
 		rm -f "${log_file}" "${tmp_manifest_path}"
 		exit 1
 	}
@@ -358,16 +358,13 @@ _snapdir_get_transfer_objects_command() {
 		rel_file_path="$(_snapdir_get_object_rel_path "${checksum}")"
 		if ! test -f "${target_dir}/${rel_file_path}"; then
 			# redirect stdout and stderr to the temporary file $log_file but also send stdout to stdout and stderr to stderr
-			echo "nice ${_SNAPDIR_S3_STORE_BIN_PATH} fetch --checksum \"${checksum}\" --source-path \"${rel_file_path}\" --target-path \"${target_dir}/${rel_file_path}\" --log-file \"$log_file\" & "
+			echo "nice ${_SNAPDIR_S3_STORE_BIN_PATH} fetch --store \"${store}\" --checksum \"${checksum}\" --source-path \"${rel_file_path}\" --target-path \"${target_dir}/${rel_file_path}\" --log-file \"$log_file\" & "
 			total_files=$((total_files + 1))
 		fi
 	done
 
 	if [[ $total_files -eq 0 ]]; then
 		echo 'echo "No new objects to fetch.";'
-	else
-		# wait for individual commands to finish
-		echo "wait -n;"
 	fi
 }
 
@@ -461,7 +458,6 @@ _snapdir_s3_store_get_remote_md5sums() {
 	# You should not rely on this method for anything other than testing
 	# since it is very slow and does not support pagination.
 	set -eEuo pipefail
-	echo aws s3api list-objects-v2 --bucket "${_SNAPDIR_STORE_BUCKET}" --prefix "${1:?Missing remote directory}" 1>&2
 	aws s3api list-objects-v2 --bucket "${_SNAPDIR_STORE_BUCKET}" --prefix "${1:?Missing remote directory}" |
 		grep -E '"(Key|ETag)":' |
 		cut -d':' -f2 |
@@ -500,7 +496,7 @@ snapdir_s3_store_test() (
 		export PATH="$HOME/.cache/snapdir/bin:$PATH"
 		(
 			set -eEuo pipefail
-			which aws >/dev/null || {
+			aws --version >/dev/null || {
 				echo "Missing aws, installing..."
 				cd /tmp
 				curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
@@ -650,8 +646,9 @@ ${bar_md5sum}  ${store_dir}/.objects/${bar_path}" | sort -k2)
 		# --------------------------------------------------------------------------------
 		result=$("${snapdir}" fetch --store "${store}" --id "${simple_manifest_id}" --verbose 2>&1 || echo "")
 
+		# echo "${snapdir}" fetch --store "${store}" --id "${simple_manifest_id}" --verbose
 		# --------------------------------------------------------------------------------
-		# tree -a "${_SNAPDIR_TEST_TMP_DIR}"
+		# tree -a "${_SNAPDIR_CACHE_DIR}"
 
 		check "should fetch the manifest"
 		test -f "${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}" || fail "Expected '${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}' to exist. Got output: '$result'"
@@ -675,11 +672,12 @@ ${bar_md5sum}  ${store_dir}/.objects/${bar_path}" | sort -k2)
 		check "should fail when the manifest has been tampered with"
 		cp "${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}" "${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}.original"
 		echo "tampered" >"${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}"
-		s3 upload-file --only-show-errors "${_SNAPDIR_STORE_BUCKET}" "${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}" "${_SNAPDIR_CACHE_DIR#/}/.manifests/${simple_manifest_path}" >/dev/null
+
+		aws s3 cp --only-show-errors "${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}" "s3://${_SNAPDIR_STORE_BUCKET}/${_SNAPDIR_CACHE_DIR#/}/.manifests/${simple_manifest_path}" >/dev/null
 		result=$("${snapdir}" fetch --dryrun --store "${store}" --id "${simple_manifest_id}" 2>&1 || echo "")
 		# restore tampered file
 		mv "${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}.original" "${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}"
-		s3 upload-file --only-show-errors "${_SNAPDIR_STORE_BUCKET}" "${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}" "${_SNAPDIR_CACHE_DIR#/}/.manifests/${simple_manifest_path}" >/dev/null
+		aws s3 cp --only-show-errors "${_SNAPDIR_CACHE_DIR}/.manifests/${simple_manifest_path}" "s3://${_SNAPDIR_STORE_BUCKET}/${_SNAPDIR_CACHE_DIR#/}/.manifests/${simple_manifest_path}" >/dev/null
 		grep -q "error: Manifest for snapshot '${simple_manifest_id}' does not match the snapshot id." <<<"${result}" || fail "Expected 'error: Manifest for snapshot '${simple_manifest_id}' does not match the snapshot id.' but got '$result'" && pass
 
 		# --------------------------------------------------------------------------------
@@ -717,7 +715,7 @@ if [[ "$(uname -s)" == "Darwin" ]]; then
 		echo "$(cd "$(dirname "$1")" || echo "" && pwd)/$(basename "$1")"
 	}
 else
-	shopt -s inherit_errexit
+
 	_snapdir_s3_store_readlink() {
 		readlink -f "$1"
 	}
@@ -737,7 +735,16 @@ if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
 	export _SNAPDIR_S3_STORE_BIN_PATH="${_SNAPDIR_S3_STORE_BIN_PATH:-$(_snapdir_s3_store_readlink "${BASH_SOURCE[0]}")}"
 	# import snapdir functions and environment variables,
 	# we'll need them to resolve directories, logging and testing.
-	_SNAPDIR_BIN_PATH="$(which snapdir || echo "$(dirname "${_SNAPDIR_S3_STORE_BIN_PATH}")/snapdir")"
+	# hide stderr
+	_SNAPDIR_BIN_PATH="$(dirname "${_SNAPDIR_S3_STORE_BIN_PATH}")/snapdir"
+	if ! test -f "$_SNAPDIR_BIN_PATH"; then
+		if snapdir -v 2>/dev/null >/dev/null; then
+			_SNAPDIR_BIN_PATH="snapdir"
+		else
+			echo "error: Could not find snapdir binary"
+			exit 1
+		fi
+	fi
 	export _SNAPDIR_BIN_PATH
 	# shellcheck disable=SC1090
 	. "$_SNAPDIR_BIN_PATH"
diff --git a/snapdir-test b/snapdir-test
--- a/snapdir-test
+++ b/snapdir-test
@@ -64,6 +64,11 @@
 set -eEuo pipefail
 IFS=$'\n\t'
 
+if [[ ${BASH_VERSION:0:1} -lt "4" ]]; then
+	echo "Bash version 4.0 or higher is required. You have: ${BASH_VERSION}" >&2
+	exit 1
+fi
+
 snapdir_test_run_unit_tests() {
 	set -eEuo pipefail
 	local dir
@@ -71,7 +76,13 @@ snapdir_test_run_unit_tests() {
 	SECONDS=0
 	"$dir/snapdir-manifest" test
 	"$dir/snapdir" test
-	"$dir/snapdir-file-store" test
+
+	if test -f "$dir/snapdir-file-store"; then
+		"$dir/snapdir-file-store" test
+	else
+		echo "# skipping snapdir-file-store test, $dir/snapdir-file-store not found" 2>&1
+	fi
+
 	echo "# unit tests completed in ${SECONDS} seconds"
 }
 
@@ -81,15 +92,16 @@ snapdir_test_run_integration_tests() {
 	dir="$(dirname "${BASH_SOURCE[0]}")"
 	echo "# integration tests"
 	SECONDS=0
-	if [[ ${SNAPDIR_B2_STORE_TEST_BUCKET:-} != "" ]]; then
+
+	if test -f "$dir/snapdir-b2-store" && [[ ${SNAPDIR_B2_STORE_TEST_BUCKET:-} != "" ]]; then
 		"$dir/snapdir-b2-store" test --store "b2://${SNAPDIR_B2_STORE_TEST_BUCKET}"
 	else
-		echo "# skipping snapdir-b2-store test. No SNAPDIR_B2_STORE_TEST_BUCKET provided." >&2
+		echo "# skipping snapdir-b2-store test. Missing SNAPDIR_B2_STORE_TEST_BUCKET or $dir/snapdir-b2-store" >&2
 	fi
-	if [[ ${SNAPDIR_S3_STORE_TEST_BUCKET:-} != "" ]]; then
+	if test -f "$dir/snapdir-s3-store" && [[ ${SNAPDIR_S3_STORE_TEST_BUCKET:-} != "" ]]; then
 		"$dir/snapdir-s3-store" test --store "s3://${SNAPDIR_S3_STORE_TEST_BUCKET}"
 	else
-		echo "# skipping snapdir-s3-store test. No SNAPDIR_S3_STORE_TEST_BUCKET provided." >&2
+		echo "# skipping snapdir-s3-store test. Missing SNAPDIR_S3_STORE_TEST_BUCKET or $dir/snapdir-s3-store" >&2
 	fi
 	echo "# integration tests completed in ${SECONDS} seconds"
 }
@@ -252,8 +264,30 @@ if [[ ${1:-} == -h || ${1:-} == --help ]]; then
 	_snapdir_test_help
 fi
 
+if [[ "$(uname -s)" == "Darwin" ]]; then
+	_snapdir_test_readlink() {
+		echo "$(cd "$(dirname "$1")" || echo "" && pwd)/$(basename "$1")"
+	}
+else
+
+	_snapdir_test_readlink() {
+		readlink -f "$1"
+	}
+fi
+
 # Run if is not sourced
 if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
+	export _SNAPDIR_TEST_BIN_PATH="${_SNAPDIR_TEST_BIN_PATH:-$(_snapdir_test_readlink "${BASH_SOURCE[0]}")}"
+
+	_SNAPDIR_BIN_PATH="$(dirname "${_SNAPDIR_TEST_BIN_PATH}")/snapdir"
+	if ! test -f "$_SNAPDIR_BIN_PATH"; then
+		if snapdir -v 2>/dev/null >/dev/null; then
+			_SNAPDIR_BIN_PATH="snapdir"
+		else
+			echo "error: Could not find snapdir binary"
+			exit 1
+		fi
+	fi
 	snapdir_test_run_unit_tests
 	# was integration passed?
 	if [[ ${1:-} == integration ]]; then
