Renaming versions to revisions

diff --git a/snapdir b/snapdir
--- a/snapdir
+++ b/snapdir
@@ -48,14 +48,14 @@
 #                                    it out the given path.
 #     push --store= [--id=] [PATH]   Pushes a snapshot to a store given its path or
 #                                    a staged manifest ID.
+#     revisions --context=           Get a list of snapdir IDs created on a
+#                                    context (store or abs path). Requires --logger.
 #     stage DIR                      Saves into the local cache a snapshot of
 #                                    a directory.
 #     test                           Runs unit tests for snapdir.
 #     verify --id= [--purge]         Verifies the integrity of a staged snapshot.
 #     verify-cache [--purge]         Verifies the integrity of the local cache.
 #     version                        Prints the version.
-#     versions --context=            Get a list of snapdir IDs created on a context.
-#                                    Requires --logger.
 #
 # ### Arguments
 #
@@ -878,12 +878,12 @@ snapdir_verify() {
 	fi
 }
 
-#     #####  ####### #     # ####### ####### #     # #######  #####          
-#    #     # #     # ##    #    #    #        #   #     #    #     #         
-#    #       #     # # #   #    #    #         # #      #    #               
-#    #       #     # #  #  #    #    #####      #       #     #####          
-#    #       #     # #   # #    #    #         # #      #          #         
-#    #     # #     # #    ##    #    #        #   #     #    #     #         
+#     #####  ####### #     # ####### ####### #     # #######  #####
+#    #     # #     # ##    #    #    #        #   #     #    #     #
+#    #       #     # # #   #    #    #         # #      #    #
+#    #       #     # #  #  #    #    #####      #       #     #####
+#    #       #     # #   # #    #    #         # #      #          #
+#    #     # #     # #    ##    #    #        #   #     #    #     #
 #     #####  ####### #     #    #    ####### #     #    #     #####
 
 snapdir_contexts() {
@@ -912,13 +912,13 @@ snapdir_contexts() {
 	"${_SNAPDIR_LOGGER_BIN_PATH}" contexts
 }
 
-#       #    #     #  #####  #######  #####  ####### ####### ######   #####  
-#      # #   ##    # #     # #       #     #    #    #     # #     # #     # 
-#     #   #  # #   # #       #       #          #    #     # #     # #       
-#    #     # #  #  # #       #####    #####     #    #     # ######   #####  
-#    ####### #   # # #       #             #    #    #     # #   #         # 
-#    #     # #    ## #     # #       #     #    #    #     # #    #  #     # 
-#    #     # #     #  #####  #######  #####     #    ####### #     #  #####  
+#       #    #     #  #####  #######  #####  ####### ####### ######   #####
+#      # #   ##    # #     # #       #     #    #    #     # #     # #     #
+#     #   #  # #   # #       #       #          #    #     # #     # #
+#    #     # #  #  # #       #####    #####     #    #     # ######   #####
+#    ####### #   # # #       #             #    #    #     # #   #         #
+#    #     # #    ## #     # #       #     #    #    #     # #    #  #     #
+#    #     # #     #  #####  #######  #####     #    ####### #     #  #####
 
 snapdir_ancestors() {
 	# Get a list of ancestor snapdir IDs and the context where they where created.
@@ -949,20 +949,20 @@ snapdir_ancestors() {
 	"${_SNAPDIR_LOGGER_BIN_PATH}" ancestors --id="${id}"
 }
 
-#    #     # ####### ######   #####  ### ####### #     #  #####              
-#    #     # #       #     # #     #  #  #     # ##    # #     #             
-#    #     # #       #     # #        #  #     # # #   # #                   
-#    #     # #####   ######   #####   #  #     # #  #  #  #####              
-#     #   #  #       #   #         #  #  #     # #   # #       #             
-#      # #   #       #    #  #     #  #  #     # #    ## #     #             
-#       #    ####### #     #  #####  ### ####### #     #  #####              
+######  ####### #     # ###  #####  ### ####### #     #  #####
+#     # #       #     #  #  #     #  #  #     # ##    # #     #
+#     # #       #     #  #  #        #  #     # # #   # #
+######  #####   #     #  #   #####   #  #     # #  #  #  #####
+#   #   #        #   #   #        #  #  #     # #   # #       #
+#    #  #         # #    #  #     #  #  #     # #    ## #     #
+#     # #######    #    ###  #####  ### ####### #     #  #####
 
-snapdir_versions() {
+snapdir_revisions() {
 	# Get a list of snapdir IDs created on a specific context.
 	#
 	# Usage:
 	#
-	#     snapdir versions \
+	#     snapdir revisions \
 	#         --context="${ABSOLUTE_DIR_NAME_OR_STORE_URI}" \
 	#         [--logger="sqlite3"]
 	#
@@ -977,24 +977,23 @@ snapdir_versions() {
 	#
 	# Example:
 	#
-	#     # Gets a list of versions stored on a store
-	#     snapdir versions --context="s3://my-bucket/some/path"
+	#     # Gets a list of revisions stored on a store
+	#     snapdir revisions --context="s3://my-bucket/some/path"
 	#
-	#     # Gets a list of versions stored on a local directory
-	#     snapdir versions --context="/home/user/some/path"
+	#     # Gets a list of revisions stored on a local directory
+	#     snapdir revisions --context="/home/user/some/path"
 	#
 	set -eEuo pipefail
 	local dir="${_SNAPDIR_DIR:-""}"
-  local store="${_SNAPDIR_STORE:-""}"
-  local context="${_SNAPDIR_CONTEXT:-"${dir}${store}"}"
-  if [[ "$context" == "" ]]; then
-    echo "Missing --context" >&2
-    return 1
-  fi
+	local store="${_SNAPDIR_STORE:-""}"
+	local context="${_SNAPDIR_CONTEXT:-"${dir}${store}"}"
+	if [[ $context == "" ]]; then
+		echo "Missing --context" >&2
+		return 1
+	fi
 	_snapdir_ensure_logger
-	"${_SNAPDIR_LOGGER_BIN_PATH}" versions --context="${context}"
+	"${_SNAPDIR_LOGGER_BIN_PATH}" revisions --context="${context}"
 }
-
 
 #    #     # ####### ######  ### ####### #     #     #####     #     #####  #     # #######
 #    #     # #       #     #  #  #        #   #     #     #   # #   #     # #     # #
@@ -1120,7 +1119,7 @@ _snapdir_run() (
 	fi
 
 	set -eEuo pipefail
-	local subcommands="manifest|id|stage|checkout|fetch|pull|push|verify|verify-cache|flush-cache|test|defaults|contexts|ancestors|versions"
+	local subcommands="manifest|id|stage|checkout|fetch|pull|push|verify|verify-cache|flush-cache|test|defaults|contexts|ancestors|revisions"
 	local boolean_args="debug|force|linked|keep|purge|stage|verbose|dryrun|context"
 	local value_required_args="id|store|cache_dir|paths|exclude|logger"
 	local legal_argument_keys="${boolean_args}|${value_required_args}"
@@ -1172,7 +1171,7 @@ _snapdir_run() (
 	local options=""
 	while [ $# -gt 0 ]; do
 		case "$1" in
-		manifest | id | stage | checkout | fetch | pull | push | verify | verify-cache | flush-cache | test | defaults | contexts | ancestors | versions)
+		manifest | id | stage | checkout | fetch | pull | push | verify | verify-cache | flush-cache | test | defaults | contexts | ancestors | revisions)
 			# if command is already set, compain about multiple commands
 			if [ -n "$command" ]; then
 				echo "error: multiple commands specified: $command $1" >&2
@@ -1579,7 +1578,7 @@ _snapdir_tmp_id() {
 
 _snapdir_ensure_logger() {
 	set -eEuo pipefail
-	if [[ "${_SNAPDIR_LOGGER_BIN_PATH:-""}" == "" ]]; then
+	if [[ ${_SNAPDIR_LOGGER_BIN_PATH:-""} == "" ]]; then
 		echo "error: Missing SNAPDIR_LOGGER or --logger" >&2
 		return 1
 	fi
@@ -1588,9 +1587,9 @@ _snapdir_ensure_logger() {
 _snapdir_enable_event_logger() {
 	_SNAPDIR_LOGGER_BIN_PATH=""
 	local logger="${SNAPDIR_LOGGER:-"${_SNAPDIR_LOGGER:-""}"}"
-	if [[ "$logger" != "" ]]; then
+	if [[ $logger != "" ]]; then
 		_SNAPDIR_LOGGER_BIN_PATH="${_SNAPDIR_BIN_DIR}/snapdir-${logger}-logger"
-		command -v "$_SNAPDIR_LOGGER_BIN_PATH" > /dev/null || {
+		command -v "$_SNAPDIR_LOGGER_BIN_PATH" >/dev/null || {
 			echo "error: Logger '${logger}' not found." >&2
 			return 1
 		}
@@ -1599,7 +1598,7 @@ _snapdir_enable_event_logger() {
 
 _snapdir_log_event() {
 	set -eEuo pipefail
-	if [[ "${_SNAPDIR_LOGGER_BIN_PATH:-""}" != "" ]]; then
+	if [[ ${_SNAPDIR_LOGGER_BIN_PATH:-""} != "" ]]; then
 		local event="${1:?Missing event as arg 1}"
 		local snapdir_id="${2:?Missing snapdir_id as arg 2}"
 		local context="${3:?Missing context as arg 3}"
@@ -2102,25 +2101,24 @@ $simple_manifest" | "${snapshot}" id "${_dir}" 2>&1 || echo "")
 		result="$("${snapshot}" version)"
 		echo "${result}" | grep -q "^[0-9]*\.[0-9]*\.[0-9]*$" || fail "Expected semver version, got: ${result}" && pass
 
-
 		# --------------------------------------------------------------------------------
 		# snapshot logger methods
 		# --------------------------------------------------------------------------------
 		describe "snapshot logger methods"
-		if [[ "${SNAPDIR_LOGGER-""}" != "" ]]; then
+		if [[ ${SNAPDIR_LOGGER-""} != "" ]]; then
 			check "should get contexts"
-			result=$("${snapshot}" contexts 2>&1 || echo "");
+			result=$("${snapshot}" contexts 2>&1 || echo "")
 			grep -E -q "($nested_manifest_id|$simple_manifest_id)" <<<"$result" || fail "Expected contexts to contain '${nested_manifest_id}' or '${simple_manifest_id}', got: '$result'"
 			pass
-			
+
 			check "should get ancestors"
-			result=$("${snapshot}" ancestors --id="${nested_manifest_id}" 2>&1 || echo "");
+			result=$("${snapshot}" ancestors --id="${nested_manifest_id}" 2>&1 || echo "")
 			grep -q "id\":\"${simple_manifest_id}\"" <<<"$result" || fail "Expected simple manifest id to be ancestor of nested manifest id, got: '$result'"
 			pass
 
-			check "should get versions"
-			result=$("${snapshot}" versions --context="${_dir}" 2>&1 || echo "");
-			tail -1 <<<"$result" | grep -q "previous_id\":null" || fail "Unexpected previous_id on last version"
+			check "should get revisions"
+			result=$("${snapshot}" revisions --context="${_dir}" 2>&1 || echo "")
+			tail -1 <<<"$result" | grep -q 'previous_id":null' || fail "Unexpected previous_id on last version"
 			grep -q "id\":\"${simple_manifest_id}\",\"previous_id\":\"${nested_manifest_id}" <<<"$result" || fail "Expected nested/simple manifest id back and forth"
 			grep -q "id\":\"${nested_manifest_id}\",\"previous_id\":\"${simple_manifest_id}" <<<"$result" || fail "Expected nested/simple manifest id back and forth"
 			pass
@@ -2128,7 +2126,7 @@ $simple_manifest" | "${snapshot}" id "${_dir}" 2>&1 || echo "")
 		else
 			skip "should get contexts"
 			skip "should get ancestors"
-			skip "should get versions"
+			skip "should get revisions"
 		fi
 	}
 
diff --git a/snapdir-sqlite3-logger b/snapdir-sqlite3-logger
--- a/snapdir-sqlite3-logger
+++ b/snapdir-sqlite3-logger
@@ -14,11 +14,11 @@ IFS=$'\n\t'
 
 snapdir_sqlite3_logger_log() {
 	set -eEuo pipefail
-  local event="${_SNAPDIR_SQLITE3_LOGGER_EVENT:?Missing --event}"
-  local id="${_SNAPDIR_SQLITE3_LOGGER_ID:?Missing --id}"
-  local context="${_SNAPDIR_SQLITE3_LOGGER_CONTEXT:?Missing --context}"
+	local event="${_SNAPDIR_SQLITE3_LOGGER_EVENT:?Missing --event}"
+	local id="${_SNAPDIR_SQLITE3_LOGGER_ID:?Missing --id}"
+	local context="${_SNAPDIR_SQLITE3_LOGGER_CONTEXT:?Missing --context}"
 	sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
-		INSERT INTO event_log (event, id, context) VALUES ('${event}', '${id}', '${context}');
+		INSERT INTO snapdir_event_log (event, id, context) VALUES ('${event}', '${id}', '${context}');
 	EOF
 	snapdir_sqlite3_logger_save "${context}" "$id"
 }
@@ -27,22 +27,23 @@ snapdir_sqlite3_logger_save() {
 	# Saves into the DB a new manifest entry. This is called
 	# after the manifest has been saved to disk.
 	set -eEuo pipefail
-  local context="${1:-${_SNAPDIR_SQLITE3_LOGGER_CONTEXT:?Missing --context}}"
+	local context="${1:-${_SNAPDIR_SQLITE3_LOGGER_CONTEXT:?Missing --context}}"
 	local id="${2:-${_SNAPDIR_SQLITE3_LOGGER_ID:?Missing --id}}"
 	local previous_id
-	previous_id="$(sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
-		SELECT id FROM snapshots 
-			WHERE context='${context}'
-		ORDER BY created_at DESC LIMIT 1;
-	EOF
+	previous_id="$(
+		sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
+			SELECT id FROM snapdir_history 
+				WHERE context='${context}'
+			ORDER BY created_at DESC LIMIT 1;
+		EOF
 	)"
-	# subsequent snapshots will not be logged
-	if [[ "${previous_id}" == "${id}" ]]; then
+	# subsequent snapdir_history will not be logged
+	if [[ ${previous_id} == "${id}" ]]; then
 		return 0
 	fi
 	previous_id="${previous_id:-"NULL"}"
 	sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
-		INSERT INTO snapshots 
+		INSERT INTO snapdir_history 
 			(context, id, previous_id)
 		VALUES 
 			('$context', '$id', NULLIF('$previous_id', 'NULL'));
@@ -58,8 +59,8 @@ snapdir_sqlite3_logger_contexts() {
 			'id', s1.id,
 			'context', s1.context
 		)
-		FROM snapshots s1
-			LEFT JOIN snapshots s2
+		FROM snapdir_history s1
+			LEFT JOIN snapdir_history s2
 				ON s1.context = s2.context
 				AND s1.created_at < s2.created_at
 		WHERE s2.id IS NULL
@@ -72,7 +73,7 @@ snapdir_sqlite3_logger_ancestors() {
 	local id="${_SNAPDIR_SQLITE3_LOGGER_ID:?Missing --id}"
 	local context="${_SNAPDIR_SQLITE3_LOGGER_CONTEXT:-""}"
 	local context_condition=""
-	if [[ "$context" != "" ]]; then
+	if [[ $context != "" ]]; then
 		context_condition=" AND context='${context//\'/\'\'}'"
 	fi
 
@@ -82,23 +83,23 @@ snapdir_sqlite3_logger_ancestors() {
 			'id', previous_id,
 			'context', context
 		)
-		FROM snapshots WHERE (
+		FROM snapdir_history WHERE (
 			id = '$id' AND previous_id IS NOT NULL $context_condition
 		) ORDER BY created_at DESC;
 	EOF
 }
 
-snapdir_sqlite3_logger_versions() {
+snapdir_sqlite3_logger_revisions() {
 	# prints a list of ids and their creation dates as timestamps for a given context
 	set -eEuo pipefail
-  local context="${_SNAPDIR_SQLITE3_LOGGER_CONTEXT:?Missing --context}"
+	local context="${_SNAPDIR_SQLITE3_LOGGER_CONTEXT:?Missing --context}"
 	sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
 		SELECT json_object(
 			'created_at', STRFTIME('%Y-%m-%d %H:%M:%f', created_at),
 			'id', id,
 			'previous_id', previous_id
 		)
-		FROM snapshots WHERE context='$context' ORDER BY created_at DESC;
+		FROM snapdir_history WHERE context='$context' ORDER BY created_at DESC;
 	EOF
 }
 
@@ -111,7 +112,7 @@ _snapdir_sqlite3_logger_run() (
 		echo "snapdir-sqlite3-logger ${@}" >>"${_SNAPDIR_RUN_LOG_PATH}"
 	fi
 
-	local subcommands="save|versions|contexts|ancestors|log"
+	local subcommands="save|revisions|contexts|ancestors|log"
 	local boolean_args="debug|verbose"
 	local value_required_args="id|context|event"
 	local legal_argument_keys="${boolean_args}|${value_required_args}"
@@ -129,48 +130,48 @@ _snapdir_sqlite3_logger_run() (
 		}
 	}
 
-_snapdir_sqlite3_logger_ensure_db() {
-	if test -f "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}"; then
-		# if "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" is older than "${_SNAPDIR_BIN_DIR}/snapdir"
-		# attempt to set the version
-		if [[ "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" -ot "${_SNAPDIR_BIN_DIR}/snapdir" ]]; then
-			# Updates the version so that we can determine the
-			# version in which each snapshots entry was created.
-			sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}"  <<-EOF
-			INSERT OR IGNORE INTO snapdir_versions (version) VALUES ("${_SNAPDIR_VERSION}");
-			EOF
+	_snapdir_sqlite3_logger_ensure_db() {
+		if test -f "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}"; then
+			# if "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" is older than "${_SNAPDIR_BIN_DIR}/snapdir"
+			# attempt to set the version
+			if [[ ${SNAPDIR_SQLITE3_LOGGER_DB_PATH} -ot "${_SNAPDIR_BIN_DIR}/snapdir" ]]; then
+				# Updates the version so that we can determine the
+				# version in which each snapdir_history entry was created.
+				sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
+					INSERT OR IGNORE INTO snapdir_system (version) VALUES ("${_SNAPDIR_VERSION}");
+				EOF
+			fi
+			return 0
 		fi
-		return 0
-	fi
-	mkdir -p "$(dirname "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}")"
-	# creates a sqlite3 db with the following tables:
-	# - snapshots: id, previous_id, dirname, created_at
-	sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
-		CREATE TABLE snapdir_versions (
-			version TEXT CHECK(version REGEXP '^[0-9]+.[0-9]+.[0-9]+$' AND length(version) < 16),
-			created_at DATETIME DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')),
-			PRIMARY KEY (version, created_at)
-		);
-		CREATE TABLE event_log (
-			event TEXT NOT NULL CHECK(event REGEXP '^[a-z]{,128}$'),
-			id TEXT NOT NULL CHECK(id REGEXP '^[a-f0-9]{64}$'),
-			context TEXT CHECK(context REGEXP '^(/|[a-z0-9]*://)'),
-			created_at DATETIME DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
-		);
-		# context, id, previous_id
-		CREATE TABLE snapshots (
-			id TEXT NOT NULL CHECK(id REGEXP '^[a-f0-9]{64}$'),
-			previous_id TEXT CHECK(previous_id REGEXP '^[a-f0-9]{64}$'),
-			context TEXT CHECK(context REGEXP '^(/|[a-z0-9]*://)'),
-			created_at DATETIME DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
-		);
-	EOF
+		mkdir -p "$(dirname "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}")"
+		# creates a sqlite3 db with the following tables:
+		# - snapdir_history: id, previous_id, dirname, created_at
+		sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
+			CREATE TABLE snapdir_system (
+				version TEXT CHECK(version REGEXP '^[0-9]+.[0-9]+.[0-9]+$' AND length(version) < 16),
+				created_at DATETIME DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')),
+				PRIMARY KEY (version, created_at)
+			);
+			CREATE TABLE snapdir_event_log (
+				event TEXT NOT NULL CHECK(event REGEXP '^[a-z]{,128}$'),
+				id TEXT NOT NULL CHECK(id REGEXP '^[a-f0-9]{64}$'),
+				context TEXT CHECK(context REGEXP '^(/|[a-z0-9]*://)'),
+				created_at DATETIME DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
+			);
+			# context, id, previous_id
+			CREATE TABLE snapdir_history (
+				id TEXT NOT NULL CHECK(id REGEXP '^[a-f0-9]{64}$'),
+				previous_id TEXT CHECK(previous_id REGEXP '^[a-f0-9]{64}$'),
+				context TEXT CHECK(context REGEXP '^(/|[a-z0-9]*://)'),
+				created_at DATETIME DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
+			);
+		EOF
 
-	# Sets the version of the db to help with upgrades
-	sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
-		INSERT INTO snapdir_versions (version) VALUES ("${_SNAPDIR_VERSION}");
-	EOF
-}
+		# Sets the version of the db to help with upgrades
+		sqlite3 "${SNAPDIR_SQLITE3_LOGGER_DB_PATH}" <<-EOF
+			INSERT INTO snapdir_system (version) VALUES ("${_SNAPDIR_VERSION}");
+		EOF
+	}
 
 	_snapdir_sqlite3_logger_help() {
 		_snapdir_sqlite3_logger_export_env_defaults
@@ -193,7 +194,7 @@ _snapdir_sqlite3_logger_ensure_db() {
 
 	while [ $# -gt 0 ]; do
 		case "$1" in
-		save | versions | contexts | ancestors | log | test)
+		save | revisions | contexts | ancestors | log | test)
 			command="$1"
 			shift
 			;;
@@ -295,18 +296,18 @@ snapdir_sqlite3_logger_test() (
 		# --------------------------------------------------------------------------------
 		describe "log"
 
-    check "should prevent invalid id"
+		check "should prevent invalid id"
 		result=$("$logger" log --event "manifest" --context "/foo/bar" --id "invalid" 2>&1 || echo "")
-    grep -q "CHECK constraint failed: id" <<<"$result" || fail "Expected error message for id. Got: '$result'" && pass
+		grep -q "CHECK constraint failed: id" <<<"$result" || fail "Expected error message for id. Got: '$result'" && pass
 
-    check "should prevent relative paths for context"
+		check "should prevent relative paths for context"
 		result=$("$logger" log --event "manifest" --context "foo/bar" --id "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789" 2>&1 || echo "")
-    grep -q "CHECK constraint failed: context" <<<"$result" || fail "Expected error message for context. Got: '$result'" && pass
+		grep -q "CHECK constraint failed: context" <<<"$result" || fail "Expected error message for context. Got: '$result'" && pass
 
-    check "should save event"
+		check "should save event"
 		result=$("$logger" log --event "manifest" --context "s3://foo" --id "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" 2>&1 || echo "")
-    test "$result" == "" || fail "Unexpected output: '$result'"
-		test "$(sqlite3 "$SNAPDIR_SQLITE3_LOGGER_DB_PATH" "select event,id,context from event_log")" == "manifest|aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|s3://foo" && pass
+		test "$result" == "" || fail "Unexpected output: '$result'"
+		test "$(sqlite3 "$SNAPDIR_SQLITE3_LOGGER_DB_PATH" "select event,id,context from snapdir_event_log")" == "manifest|aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|s3://foo" && pass
 
 		# --------------------------------------------------------------------------------
 		"$logger" log --event "manifest" --context "s3://bar" --id "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
@@ -352,17 +353,17 @@ snapdir_sqlite3_logger_test() (
 		test "$(echo "$result" | wc -l)" == "1" || fail "Found more ancestors than expected."
 		pass
 
-		describe "versions"
+		describe "revisions"
 
-		check "should not return versions for an invalid context"
-		result="$("$logger" versions --context "/not/avail" 2>&1 || echo "")"
+		check "should not return revisions for an invalid context"
+		result="$("$logger" revisions --context "/not/avail" 2>&1 || echo "")"
 		test "$result" == "" || fail "Unexpected output: '$result'" && pass
 
-		check "should return versions for a valid context"
-		result="$("$logger" versions --context "s3://bar" 2>&1 || echo "")"
-		grep "id\":\"ccc" <<<"$result" | grep -q "previous_id\":\"aaaaa" || fail "Expected id 'ccc...' with previous_id 'aaa...'. Got: '$result'"
-		grep "id\":\"aaa" <<<"$result" | grep -q "previous_id\":null" || fail "Expected id 'aaa...' with previous_id 'null'. Got: '$result'"
-		test "$(echo "$result" | wc -l)" == "2" || fail "Found more versions than expected."
+		check "should return revisions for a valid context"
+		result="$("$logger" revisions --context "s3://bar" 2>&1 || echo "")"
+		grep 'id":"ccc' <<<"$result" | grep -q 'previous_id":"aaaaa' || fail "Expected id 'ccc...' with previous_id 'aaa...'. Got: '$result'"
+		grep 'id":"aaa' <<<"$result" | grep -q 'previous_id":null' || fail "Expected id 'aaa...' with previous_id 'null'. Got: '$result'"
+		test "$(echo "$result" | wc -l)" == "2" || fail "Found more revisions than expected."
 		pass
 
 	}
