Adding `snapdir command --help`

diff --git a/snapdir b/snapdir
--- a/snapdir
+++ b/snapdir
@@ -2,11 +2,83 @@
 
 # # snapdir 0.1.1
 #
-# ## Description:
+# Create authenticated directory snapshots and save them on pluggable stores.
 #
-#     Audit and distribute authenticated directory snapshots.
+# ## Usage
 #
-# ## License
+#     snapdir [OPTIONS] [SUBCOMMAND] [ARGUMENTS]
+#
+# ### Options
+#
+#     --cache-dir=DIR        Directory where the object cache is stored.
+#     --debug                Enable debug output.
+#     --dryrun               Run without making any changes.
+#     --force                Force an action to run.
+#     --help, -h             Prints help message.
+#     --id=ID                Manifest ID to use.
+#     --keep                 Keeps the staging directory.
+#     --linked               Use symlinks instead of copies.
+#     --path=PATH            Partial path for checkout operations.
+#     --purge                Purges objects with invalid checksums.
+#     --store=URI            Store URI protocol://location/path.
+#     --verbose              Enable verbose output.
+#     --version, -v          Prints version.
+#
+# ### Commands
+#
+#
+#     checkout --id= [--linked] DIR  Checkout a snapshot to a directory.
+#     defaults                       Prints default settings and arguments.
+#     fetch --id= --store=           Fetch a snapshot from a store.
+#     flush-cache                    Flushes the local cache.
+#     help                           Prints help information.
+#     id [PATH]                      Prints the manifest ID of a directory
+#                                    or manifest provided via stdin.
+#     manifest PATH                  Prints the manifest of a directory.
+#     pull --id= --store= PATH       Fetches a snapshot from a store and checks
+#                                    it out the given path.
+#     push --store= [--id=] [PATH]   Pushes a snapshot to a store given its path or
+#                                    a staged manifest ID.
+#     stage DIR                      Saves into the local cache a snapshot of
+#                                    a directory.
+#     test                           Runs unit tests for snapdir.
+#     verify --id= [--purge]         Verifies the integrity of a staged snapshot.
+#     verify-cache [--purge]         Verifies the integrity of the local cache.
+#     version                        Prints the version.
+#
+# ### Arguments
+#
+#     <DIR>    Directory path for snapshot operations.
+#     <PATH>   Path to an object in a manifest to cherry-pick.
+#
+# ### Environment variables
+#
+#     SNAPDIR_MANIFEST_CONTEXT    Context string for deriving key in keyed mode.
+#                                 This only works with b3sum.
+#     SNAPDIR_MANIFEST_EXCLUDE    Default grep -v rule for --exclude="system".
+#
+# ### Examples
+#
+#     # generates a manifest for the current directory
+#     snapdir manifest ./
+#
+#     # generates an id for the manifest of the current directory
+#     snapdir id ./
+#
+#     # excludes files and directories matching the pattern
+#     snapdir --exclude="/(.git|.DS_Store)($|/)" manifest ./
+#
+#     # stages a snapshot of the current directory
+#     snapdir stage ./
+#
+#     # verifies a snapshot given its id, to purge invalid objects add --purge
+#     snapdir verify --verbose --id=d640dce8e26f39d4dae336a7da83478385ce52a844c1d9b91f204ef83c558dd2
+#
+#     # checks out a copy of the snapshot on a given directory
+#     snapdir checkout --id=d640dce8e26f39d4dae336a7da83478385ce52a844c1d9b91f204ef83c558dd2 ./two
+#
+#     # use --linked if you prefer to create a hard link and use a COW filesystem
+#     snapdir checkout --link --id=d640dce8e26f39d4dae336a7da83478385ce52a844c1d9b91f204ef83c558dd2 ./two
 #
 # LICENSE: MIT Copyright (c) 2022 Bermi Ferrer
 
@@ -245,8 +317,6 @@ snapdir_push() {
 snapdir_fetch() {
 	# Retrieves a snapshot from a store and saves it in the local cache.
 	#
-	# Returns: No output unless in --verbose mode. Exit code 1 in case of error.
-	#
 	# Usage:
 	#
 	#     snapdir fetch \
@@ -254,6 +324,8 @@ snapdir_fetch() {
 	#         --id="${ID}" \
 	#         [--(dryrun|verbose)] \
 	#         [--cache-dir="${CACHE_DIR}"]
+	#
+	# Returns: No output unless in --verbose mode. Exit code 1 in case of error.
 	#
 	# Examples:
 	#
@@ -347,8 +419,6 @@ snapdir_fetch() {
 snapdir_pull() {
 	# Fetches a snapshot from a store and checks it out on a given directory.
 	#
-	# Returns: No output unless in --verbose mode. Exit code 1 in case of error.
-	#
 	# Usage:
 	#
 	#     snapdir pull \
@@ -357,6 +427,8 @@ snapdir_pull() {
 	#         [--(dryrun|verbose|force|linked)] \
 	#         [--cache-dir="${CACHE_DIR}"]
 	#         ["${DIR}"]
+	#
+	# Returns: No output unless in --verbose mode. Exit code 1 in case of error.
 	#
 	# Examples:
 	#
@@ -406,8 +478,6 @@ snapdir_checkout() {
 	# This only works if the files are on the same filesystem and it's only
 	# recommended for filesystems with copy-on-write (COW) support.
 	#
-	# Returns: No output unless in --verbose mode. Exit code 1 in case of error.
-	#
 	# Usage:
 	#
 	#     snapdir checkout \
@@ -416,6 +486,8 @@ snapdir_checkout() {
 	#         [--(dryrun|verbose|force|linked)] \
 	#         [--cache-dir="${CACHE_DIR}"]
 	#         ["${DIR}"]
+	#
+	# Returns: No output unless in --verbose mode. Exit code 1 in case of error.
 	#
 	# Examples:
 	#
@@ -563,13 +635,13 @@ snapdir_checkout() {
 snapdir_stage() {
 	# Stages the files in a given directory into the local cache.
 	#
-	# Returns: The manifest id or the staging directory when --keep is provided.
-	#
 	# Usage:
 	#
 	#     snapdir stage ["${DIR}"] \
 	#         [--cache-dir="${CACHE_DIR}"]
 	#         [--(keep|verbose)]
+	#
+	# Returns: The manifest id or the staging directory when --keep is provided.
 	#
 	# Examples:
 	#
@@ -681,13 +753,13 @@ snapdir_stage() {
 snapdir_verify() {
 	# Verifies the integrity of a snapshot.
 	#
-	# Returns: Exits with 0 if the snapshot is valid, 1 otherwise.
-	#
 	# Usage:
 	#     snapdir verify \
 	#         --id="${ID}" \
 	#         [--cache-dir="${CACHE_DIR}"]
 	#         [--(purge|verbose)]
+	#
+	# Returns: Exits with 0 if the snapshot is valid, 1 otherwise.
 	#
 	# Examples:
 	#
@@ -734,13 +806,13 @@ snapdir_verify() {
 snapdir_verify_cache() {
 	# Verifies the integrity of all the objects in the cache.
 	#
-	# Returns: Exits with 0 if all the objects are valid, 1 otherwise.
-	#
 	# Usage:
 	#
 	#     snapdir verify-cache \
 	#         [--cache-dir="${CACHE_DIR}"]
 	#         [--(purge|verbose)]
+	#
+	# Returns: Exits with 0 if all the objects are valid, 1 otherwise.
 	#
 	# Example:
 	#
@@ -818,6 +890,14 @@ snapdir_defaults() {
 	} | sort -u
 }
 
+######  ######  ### #     #    #    ####### #######    ####### #     #  #####
+#     # #     #  #  #     #   # #      #    #          #       ##    # #     #
+#     # #     #  #  #     #  #   #     #    #          #       # #   # #
+######  ######   #  #     # #     #    #    #####      #####   #  #  #  #####
+#       #   #    #   #   #  #######    #    #          #       #   # #       #
+#       #    #   #    # #   #     #    #    #          #       #    ## #     #
+#       #     # ###    #    #     #    #    #######    #       #     #  #####
+
 ######  #     # #     #
 #     # #     # ##    #
 #     # #     # # #   #
@@ -871,7 +951,12 @@ _snapdir_run() (
 
 	_snapdir_help() {
 		_snapdir_export_env_defaults
-		sed '/# LICENSE: MIT Copyright (c) 2022 Bermi Ferrer/q; 1,2d' "$_SNAPDIR_BIN_PATH" | sed -E 's|^# ?||g; $d' | more
+		local command="${1:-""}"
+		if [[ ${command} == "" ]]; then
+			sed '/# LICENSE: MIT Copyright (c) 2022 Bermi Ferrer/q; 1,2d' "$_SNAPDIR_BIN_PATH" | sed -E 's|^# ?||g; $d' | more
+		else
+			_snapdir_command_help "snapdir_${command//-/_}" <"$_SNAPDIR_BIN_PATH" | more
+		fi
 		exit 0
 	}
 
@@ -881,6 +966,7 @@ _snapdir_run() (
 	local value
 	local is_boolean
 	local subcommand_candidate="${1:-""}"
+	local show_help=false
 	while [ $# -gt 0 ]; do
 		case "$1" in
 		manifest | id | stage | checkout | fetch | pull | push | verify | verify-cache | flush-cache | test | defaults)
@@ -893,7 +979,8 @@ _snapdir_run() (
 			shift
 			;;
 		help | -h | --help)
-			_snapdir_help
+			show_help=true
+			shift
 			;;
 		version | -v | --version)
 			echo "${_SNAPDIR_VERSION}"
@@ -942,17 +1029,13 @@ _snapdir_run() (
 		fi
 	fi
 
+	if [[ ${show_help} == "true" ]]; then
+		_snapdir_help "$command"
+	fi
+
 	_snapdir_export_env_defaults "${command}"
 	eval "snapdir_${command//-/_} $positional_args ${*:2}"
 )
-
-######  ######  ### #     #    #    ####### #######    ####### #     #  #####
-#     # #     #  #  #     #   # #      #    #          #       ##    # #     #
-#     # #     #  #  #     #  #   #     #    #          #       # #   # #
-######  ######   #  #     # #     #    #    #####      #####   #  #  #  #####
-#       #   #    #   #   #  #######    #    #          #       #   # #       #
-#       #    #   #    # #   #     #    #    #          #       #    ## #     #
-#       #     # ###    #    #     #    #    #######    #       #     #  #####
 
 _snapdir_get_fetch_snapdir_manifest_command() {
 	set -eEuo pipefail
@@ -1049,6 +1132,40 @@ _snapdir_get_base_dir() {
 		return 1
 	fi
 	echo "${base_dir}"
+}
+
+_snapdir_command_help() {
+	set -eEuo pipefail
+	local command="${1:?Missing command}"
+	local contents
+	contents=$(cat)
+	echo "$contents" | _snapdir_get_function_body "$command" | sed -E 's|[\t]*# ?|#|' | _snapdir_get_doc_block_from_function_body
+}
+
+_snapdir_get_function_body() {
+	set -eEuo pipefail
+	local command="${1// /_}"
+	local function_name
+	function_name="$(echo "$command" | tr '-' '_')"
+	local script_contents
+	script_contents=$(cat)
+	echo "$script_contents" | sed -E -n "/^${function_name} ?\(\)/,/^}/p" | sed -E -n "/^${function_name} ?\(\)/,/^}/p" | grep -v "${function_name}(" | grep -v "^}"
+}
+
+_snapdir_get_doc_block_from_function_body() {
+	set -eEuo pipefail
+	local function_body
+	function_body="$(cat)"
+	# get the first line number that does not
+	# start with #
+	local first_line_number
+	first_line_number=$(echo "$function_body" | grep -n "^[^#]" | head -n 1 | cut -d ':' -f1 || true)
+	if [[ -z $first_line_number ]]; then
+		echo "ERROR: No documentation found"
+		return
+	fi
+	# show the first line number - 1
+	echo "$function_body" | sed -n 1,"$((first_line_number - 1))"p | sed -E 's|^#||'
 }
 
 # shellcheck disable=SC2295
@@ -1276,8 +1393,16 @@ _snapdir_dryrun_log() {
 #          #    #       #     #    #    #     #
 #          #    #######  #####     #     #####
 
+# note: using subshell – '(' instead of '{' – to avoid leaking helper functions
 snapdir_test() (
-	# note: using subshell – '(' instead of '{' – to avoid leaking helper functions
+	# Runs the tests for the snapdir command.
+	#
+	# Requires the helper script [snapdir-test](./snapdir-test) to be on the same directory.
+	#
+	# Usage:
+	#
+	#     snapdir test
+	#
 	set -eEuo pipefail
 
 	# Import test utilities
