Renaming logger to catalog

diff --git a/snapdir b/snapdir
--- a/snapdir
+++ b/snapdir
@@ -11,7 +11,7 @@
 # ### Options
 #
 #     --cache-dir=DIR        Directory where the object cache is stored.
-#     --context=DIR|STORE    Context for logger queries.
+#     --context=DIR|STORE    Context for catalog queries.
 #     --debug                Enable debug output.
 #     --dryrun               Run without making any changes.
 #     --exclude=PATTERN      Excludes paths matching PATTERN.
@@ -22,7 +22,7 @@
 #     --id=ID                Manifest ID to use.
 #     --keep                 Keeps the staging directory.
 #     --linked               Use symlinks instead of copies.
-#     --logger=NAME          Logger to use. Defaults to $SNAPDIR_LOGGER.
+#     --catalog=NAME         Catalog adapter to use. Defaults to $SNAPDIR_CATALOG.
 #     --paths=PATTERN        Only includes paths matching PATTERN
 #                            when checking out manifests.
 #     --purge                Purges objects with invalid checksums.
@@ -33,10 +33,10 @@
 # ### Commands
 #
 #     ancestors --id=                Get a list of ancestor snapdir IDs their context.
-#                                    Requires --logger.
+#                                    Requires --catalog.
 #     checkout --id= [--linked] DIR  Checkout a snapshot to a directory.
 #     contexts                       Lists directories and stores where snapshots
-#                                    have been taken or published. Requires --logger.
+#                                    have been taken or published. Requires --catalog.
 #     defaults                       Prints default settings and arguments.
 #     fetch --id= --store=           Fetch a snapshot from a store.
 #     flush-cache                    Flushes the local cache.
@@ -49,7 +49,7 @@
 #     push --store= [--id=] [PATH]   Pushes a snapshot to a store given its path or
 #                                    a staged manifest ID.
 #     revisions --context=           Get a list of snapdir IDs created on a
-#                                    context (store or abs path). Requires --logger.
+#                                    context (store or abs path). Requires --catalog.
 #     stage DIR                      Saves into the local cache a snapshot of
 #                                    a directory.
 #     test                           Runs unit tests for snapdir.
@@ -69,7 +69,7 @@
 #                                    overridden by --cache-dir.
 #     SNAPDIR_MANIFEST_CONTEXT       Context string for deriving key in keyed mode.
 #     SNAPDIR_SYSTEM_EXCLUDE_DIRS    Directories to exclude on --exclude="%system%".
-#     SNAPDIR_LOGGER                 Default logger to use when no --logger is
+#     SNAPDIR_CATALOG                 Default catalog to use when no --catalog is
 #                                    provided. Defaults to none.
 #
 # ### Examples
@@ -892,7 +892,7 @@ snapdir_contexts() {
 	# Usage:
 	#
 	#     snapdir contexts \
-	#         [--logger="sqlite3"]
+	#         [--catalog="sqlite3"]
 	#
 	# Returns: JSON lines of the form:
 	#
@@ -904,12 +904,12 @@ snapdir_contexts() {
 	#
 	# Example:
 	#
-	#     # Use the default logger defined by SNAPDIR_LOGGER
+	#     # Use the default catalog defined by SNAPDIR_CATALOG
 	#     snapdir contexts
 	#
 	set -eEuo pipefail
-	_snapdir_ensure_logger
-	"${_SNAPDIR_LOGGER_BIN_PATH}" contexts
+	_snapdir_ensure_catalog
+	"${_SNAPDIR_CATALOG_BIN_PATH}" contexts
 }
 
 #       #    #     #  #####  #######  #####  ####### ####### ######   #####
@@ -928,7 +928,7 @@ snapdir_ancestors() {
 	#     snapdir ancestors \
 	#         --id="${SNAPDIR_ID}" \
 	#         [--context="${ABSOLUTE_DIR_NAME_OR_STORE_URI}"] \
-	#         [--logger="sqlite3"]
+	#         [--catalog="sqlite3"]
 	#
 	# Returns: JSON lines of the form:
 	#
@@ -940,13 +940,13 @@ snapdir_ancestors() {
 	#
 	# Example:
 	#
-	#     # Use the default logger defined by SNAPDIR_LOGGER
+	#     # Use the default catalog defined by SNAPDIR_CATALOG
 	#     snapdir ancestors --id="${SNAPDIR_ID}"
 	#
 	set -eEuo pipefail
 	local id="${_SNAPDIR_ID:?Missing --id}"
-	_snapdir_ensure_logger
-	"${_SNAPDIR_LOGGER_BIN_PATH}" ancestors --id="${id}"
+	_snapdir_ensure_catalog
+	"${_SNAPDIR_CATALOG_BIN_PATH}" ancestors --id="${id}"
 }
 
 ######  ####### #     # ###  #####  ### ####### #     #  #####
@@ -964,7 +964,7 @@ snapdir_revisions() {
 	#
 	#     snapdir revisions \
 	#         --context="${ABSOLUTE_DIR_NAME_OR_STORE_URI}" \
-	#         [--logger="sqlite3"]
+	#         [--catalog="sqlite3"]
 	#
 	# Returns: JSON lines of the form:
 	#
@@ -991,8 +991,8 @@ snapdir_revisions() {
 		echo "Missing --context" >&2
 		return 1
 	fi
-	_snapdir_ensure_logger
-	"${_SNAPDIR_LOGGER_BIN_PATH}" revisions --context="${context}"
+	_snapdir_ensure_catalog
+	"${_SNAPDIR_CATALOG_BIN_PATH}" revisions --context="${context}"
 }
 
 #    #     # ####### ######  ### ####### #     #     #####     #     #####  #     # #######
@@ -1121,7 +1121,7 @@ _snapdir_run() (
 	set -eEuo pipefail
 	local subcommands="manifest|id|stage|checkout|fetch|pull|push|verify|verify-cache|flush-cache|test|defaults|contexts|ancestors|revisions"
 	local boolean_args="debug|force|linked|keep|purge|stage|verbose|dryrun|context"
-	local value_required_args="id|store|cache_dir|paths|exclude|logger"
+	local value_required_args="id|store|cache_dir|paths|exclude|catalog"
 	local legal_argument_keys="${boolean_args}|${value_required_args}"
 
 	parse_argument_key() {
@@ -1237,7 +1237,7 @@ _snapdir_run() (
 	fi
 
 	_snapdir_export_env_defaults "${command}"
-	_snapdir_enable_event_logger
+	_snapdir_enable_event_catalog
 	eval "snapdir_${command//-/_} $positional_args ${*:2}"
 )
 
@@ -1576,21 +1576,21 @@ _snapdir_tmp_id() {
 	echo "${RANDOM:-""}$(date +%s%N).tmp"
 }
 
-_snapdir_ensure_logger() {
+_snapdir_ensure_catalog() {
 	set -eEuo pipefail
-	if [[ ${_SNAPDIR_LOGGER_BIN_PATH:-""} == "" ]]; then
-		echo "error: Missing SNAPDIR_LOGGER or --logger" >&2
+	if [[ ${_SNAPDIR_CATALOG_BIN_PATH:-""} == "" ]]; then
+		echo "error: Missing SNAPDIR_CATALOG or --catalog" >&2
 		return 1
 	fi
 }
 
-_snapdir_enable_event_logger() {
-	_SNAPDIR_LOGGER_BIN_PATH=""
-	local logger="${SNAPDIR_LOGGER:-"${_SNAPDIR_LOGGER:-""}"}"
-	if [[ $logger != "" ]]; then
-		_SNAPDIR_LOGGER_BIN_PATH="${_SNAPDIR_BIN_DIR}/snapdir-${logger}-logger"
-		command -v "$_SNAPDIR_LOGGER_BIN_PATH" >/dev/null || {
-			echo "error: Logger '${logger}' not found." >&2
+_snapdir_enable_event_catalog() {
+	_SNAPDIR_CATALOG_BIN_PATH=""
+	local catalog_adapter="${SNAPDIR_CATALOG:-"${_SNAPDIR_CATALOG:-""}"}"
+	if [[ $catalog_adapter != "" ]]; then
+		_SNAPDIR_CATALOG_BIN_PATH="${_SNAPDIR_BIN_DIR}/snapdir-${catalog_adapter}-catalog"
+		command -v "$_SNAPDIR_CATALOG_BIN_PATH" >/dev/null || {
+			echo "error: Catalog adapter '${catalog_adapter}' not found." >&2
 			return 1
 		}
 	fi
@@ -1598,11 +1598,11 @@ _snapdir_enable_event_logger() {
 
 _snapdir_log_event() {
 	set -eEuo pipefail
-	if [[ ${_SNAPDIR_LOGGER_BIN_PATH:-""} != "" ]]; then
+	if [[ ${_SNAPDIR_CATALOG_BIN_PATH:-""} != "" ]]; then
 		local event="${1:?Missing event as arg 1}"
 		local snapdir_id="${2:?Missing snapdir_id as arg 2}"
 		local context="${3:?Missing context as arg 3}"
-		"$_SNAPDIR_LOGGER_BIN_PATH" log \
+		"$_SNAPDIR_CATALOG_BIN_PATH" log \
 			--event="$event" \
 			--id="$snapdir_id" \
 			--context="$context"
@@ -2102,10 +2102,10 @@ $simple_manifest" | "${snapshot}" id "${_dir}" 2>&1 || echo "")
 		echo "${result}" | grep -q "^[0-9]*\.[0-9]*\.[0-9]*$" || fail "Expected semver version, got: ${result}" && pass
 
 		# --------------------------------------------------------------------------------
-		# snapshot logger methods
+		# snapshot catalog methods
 		# --------------------------------------------------------------------------------
-		describe "snapshot logger methods"
-		if [[ ${SNAPDIR_LOGGER-""} != "" ]]; then
+		describe "snapshot catalog methods"
+		if [[ ${SNAPDIR_CATALOG-""} != "" ]]; then
 			check "should get contexts"
 			result=$("${snapshot}" contexts 2>&1 || echo "")
 			grep -E -q "($nested_manifest_id|$simple_manifest_id)" <<<"$result" || fail "Expected contexts to contain '${nested_manifest_id}' or '${simple_manifest_id}', got: '$result'"
diff --git a/snapdir-test b/snapdir-test
--- a/snapdir-test
+++ b/snapdir-test
@@ -118,18 +118,26 @@ _snapdir_test_run_integration_tests() {
 	echo "# integration tests completed in ${SECONDS} seconds"
 }
 
-_snapdir_test_run_logger_tests() {
+_snapdir_test_run_catalog_tests() {
 	set -eEuo pipefail
 	local dir
 	dir="$(dirname "${BASH_SOURCE[0]}")"
 	echo "# integration tests"
 	if command -v "sqlite3" >/dev/null; then
-		echo "# using sqlite3 --version: $(sqlite3 --version)"
-		export SNAPDIR_SQLITE3_LOGGER_DB_PATH="$(pwd)/snapdir-tests.db"
-		"$dir"/snapdir-sqlite3-logger test
-		SNAPDIR_LOGGER=sqlite3 "$dir"/snapdir test
+		local sqlite_min_date="2021-06-18"
+		local sqlite_release_date
+		sqlite_release_date="$(sqlite3 --version | cut -d ' ' -f 2)"
+		# only if sqlite_release_date is greater than the min date
+		if [[ $sqlite_release_date < $sqlite_min_date ]]; then
+			echo "# skipping sqlite3 test. sqlite3 version $(sqlite3 --version) is less than 3.36" >&2
+		else
+			echo "# using sqlite3 --version: $(sqlite3 --version)"
+			export SNAPDIR_SQLITE3_CATALOG_DB_PATH
+			"$dir"/snapdir-sqlite3-catalog test
+			SNAPDIR_CATALOG=sqlite3 "$dir"/snapdir test
+		fi
 	else
-		echo "# skipping sqlite3 logger test, sqlite3 not found locally" >&2
+		echo "# skipping sqlite3 catalog test, sqlite3 not found locally" >&2
 	fi
 }
 
@@ -153,7 +161,7 @@ _snapdir_test_utils() {
 		export _SNAPDIR_CACHE_DIR="${_SNAPDIR_TEST_TMP_DIR}/.cache/${_SNAPDIR_MODULE_NAME}"
 		export SNAPDIR_CACHE_DIR="${_SNAPDIR_CACHE_DIR}"
 		export _SNAPDIR_MANIFEST_CACHE_DIR="${_SNAPDIR_CACHE_DIR}"
-		export SNAPDIR_SQLITE3_LOGGER_DB_PATH="${_SNAPDIR_TEST_TMP_DIR}/logger.db"
+		export SNAPDIR_SQLITE3_CATALOG_DB_PATH="${_SNAPDIR_TEST_TMP_DIR}/catalog.db"
 
 		cd "$_SNAPDIR_TEST_TMP_DIR" || return 1
 
@@ -183,7 +191,6 @@ _snapdir_test_utils() {
 		_SNAPDIR_TEST_TEARDOWN_COMPLETE=true
 		teardown_suite
 		rm -rf "$_SNAPDIR_TEST_TMP_DIR"
-		rm -rf "$(pwd)/snapdir-tests.db"
 		# exit with not ok if _SNAPDIR_TEST_TOTAL_CHECKS is not zero
 		if [[ $_SNAPDIR_TESTS_PENDING_CHECKS -gt 0 ]]; then
 			echo "not ok ${_SNAPDIR_TESTS_PENDING_CHECKS}..${_SNAPDIR_TEST_TOTAL_CHECKS} - ${_SNAPDIR_TESTS_PENDING_CHECKS} ${_SNAPDIR_TEST_SUITE_DESCRIPTION} tests pending" >&2
@@ -380,6 +387,8 @@ else
 	}
 fi
 
+export ENVIRONMENT="test"
+
 # Run if is not sourced
 if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
 	# does ${1:-} matches -h, --help or help?
@@ -387,10 +396,9 @@ if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
 		_snapdir_test_help
 		exit 0
 	fi
-	# avoid trashing the user logger if they are running the test suite
-	unset SNAPDIR_LOGGER
+	# avoid trashing the user catalog if they are running the test suite
+	unset SNAPDIR_CATALOG
 	export _SNAPDIR_TEST_BIN_PATH="${_SNAPDIR_TEST_BIN_PATH:-$(_snapdir_test_readlink "${BASH_SOURCE[0]}")}"
-	export ENVIRONMENT="test"
 	_SNAPDIR_BIN_PATH="$(dirname "${_SNAPDIR_TEST_BIN_PATH}")/snapdir"
 
 	if [[ ${1:-} == integration ]]; then
@@ -406,7 +414,7 @@ if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
 		fi
 	fi
 	_snapdir_test_run_unit_tests
-	_snapdir_test_run_logger_tests
+	_snapdir_test_run_catalog_tests
 	# was integration passed?
 	if [[ ${1:-} == integration ]]; then
 		_snapdir_test_run_integration_tests
